# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

- name: Restart sshd
  become: true
  ansible.builtin.service:
    name: 'sshd'
    state: restarted
